# Numpy

- NumPy stores data in arrays: 1D, 2D, 3D, or more dimensions.
- NumPy is usually faster for numerical operations on large datasets.
- Numeric arrays store values directly using a fixed number of bytes. Python lists store references to objects, which adds memory overhead.
- Every element in a NumPy array has the same dtype. Lists can contain different data types.
- NumPy arrays are usually stored in continuous memory. Lists store references together, but the objects they reference can be scattered.
- NumPy can multiply corresponding elements using a * b. With lists, we usually use a loop or list comprehension.
- 1 byte = 8 bits.

In [1]:
import numpy as np

# Basics

In [2]:
# Create one dimensional array
a=np.array([1,2,3,4,5],dtype='int32')
print(a)

# create two dimensional array with float datatype
b=np.array([[1.,2.,3.,4.,5.],[6.,7.,8.,9.,0.]])
print(b)

# Get dimension
print(f"Dimension of a : {a.ndim} ")
print(f"Dimension of b : {b.ndim} ")

# Get shape
print(f"Shape of a: {a.shape} ")
print(f"Shape of b: {b.shape} ")

# get type of array
print(f"Datatype of a : {a.dtype} ")
print(f"Datatype of b: {b.dtype} ")

# get bytes used by the array
a=np.array([1,2,3,4,5],dtype='int32')
print(f"Number of bytes used to store each element in the array a is {a.itemsize} ")
a=np.array([1,2,3,4,5],dtype='int8')
print(f"Number of bytes used to store each element in the array a is {a.itemsize} ")

# fine number of element in the array
print(f"Number of elements in array a : {a.size} ")
print(f"Number of elements in the array b: {b.size} ")

# Find total memory usage of each array
print(f"Total memory for array a: {a.size*a.itemsize}  ")
print(f"Total memory for array b: {b.size*b.itemsize} ")

# use nbytes
print(f"memory used by array elements in bytes {a.nbytes} ")

[1 2 3 4 5]
[[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]
Dimension of a : 1 
Dimension of b : 2 
Shape of a: (5,) 
Shape of b: (2, 5) 
Datatype of a : int32 
Datatype of b: float64 
Number of bytes used to store each element in the array a is 4 
Number of bytes used to store each element in the array a is 1 
Number of elements in array a : 5 
Number of elements in the array b: 10 
Total memory for array a: 5  
Total memory for array b: 80 
memory used by array elements in bytes 5 


# Accessing/changing specific elements/row/column

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(f"A :\n{a}\nDimension: {a.ndim}")

# Get specific element
print(f"Get second row 6th element: {a[1,5]} ")

# get Specific row
print(f"Get first row : {a[0]} ")

# Get specific column
print(f"Get third column: {a[:,2]} ")

# start index, end index , step count
print(f"Get number 2 4 6 : {a[0,1:6:2]} ")

# Change a specific value
print(f"Before change\n{a} ")
a[1,5]=100
print(f"\nAfter change\n{a}")

# CHange all the element third column to one value
print(f"Before change\n{a} ")
a[:,2]=5
print(f"After change\n{a} ")

# CHange all the element third column to differnt value
print(f"Before change\n{a} ")
a[:,2]=[1000,5000]
print(f"After change\n{a} ")

# Create 3 dimensional array
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"3 Dimensional array:\n{b} ")

# get number 4
print(f"Number 4: {b[0,1,1]}  ")
print(f"First set:\n{b[0,:,:]}")

# Change the value
print(f"Before change:\n{b} ")
b[1,:,:]=[[100,100],[100,100]]
print(f"After change:\n{b} ")

A :
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Dimension: 2
Get second row 6th element: 13 
Get first row : [1 2 3 4 5 6 7] 
Get third column: [ 3 10] 
Get number 2 4 6 : [2 4 6] 
Before change
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] 

After change
[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 100  14]]
Before change
[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 100  14]] 
After change
[[  1   2   5   4   5   6   7]
 [  8   9   5  11  12 100  14]] 
Before change
[[  1   2   5   4   5   6   7]
 [  8   9   5  11  12 100  14]] 
After change
[[   1    2 1000    4    5    6    7]
 [   8    9 5000   11   12  100   14]] 
3 Dimensional array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
Number 4: 4  
First set:
[[1 2]
 [3 4]]
Before change:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
After change:
[[[  1   2]
  [  3   4]]

 [[100 100]
  [100 100]]] 


# Initialize different types of arrays

In [4]:
#### Create zeros and one array
print(f"Zero array:\n{np.zeros(shape=(2,10))} ")
print(f"Ones array:\n{np.ones(shape=(4,2,3),dtype='float32')} ")

# Create array with differnet number
print(f"Array with 200 value:\n{np.full(shape=(10,5),fill_value=200,dtype='float32')} ")

# Create array with referencw with other array shape
a=np.array([[1,2,3,4,5,6,7],[8,9,1,2,3,4,5]])
new=np.full_like(a,fill_value=20)
print(f"new array:\n{new} ")
# if you want to use full instead of full_like
new=np.full(shape=a.shape,fill_value=0)
print(f"new array:\n{new} ")

# creat random value array
print(f"Random array:\n{np.random.rand(4,2)} ")
print(f"Random array:\n{np.random.random_sample(a.shape)} ")

# Get random int value
print(f"Random int array:\n{np.random.randint(7,10,size=(10,5))} ")

# Create identity matrix
print(f"Identity matrix:\n{np.identity(10)} ")

# repeat array
arr=np.array([[1,2,3]])
repeat=np.repeat(arr,4,axis=0)
print(repeat)

Zero array:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 
Ones array:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] 
Array with 200 value:
[[200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]
 [200. 200. 200. 200. 200.]] 
new array:
[[20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20]] 
new array:
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 
Random array:
[[0.626469   0.1098827 ]
 [0.94530501 0.9771369 ]
 [0.48914396 0.9255462 ]
 [0.11517666 0.03306537]] 
Random array:
[[0.78668269 0.20814647 0.74398963 0.74718442 0.6181439  0.34723312
  0.46866923]
 [0.35026255 0.25816058 0.32230799 0.06095785 0.73278737 0.29899152
  0.47721039]] 
Random int array:
[[8 9 7 7 9]
 [9 9 8 7 9]
 [7 8 7 9 9]
 [9 7 7 9 8]
 [8 9 8 8 7]
 [7 

In [5]:
# Make this array 
output=np.ones(shape=(5,5))
zero=np.zeros(shape=(3,3))
zero[1,1]=9
output[1:4,1:4]=zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying the array

In [6]:
a=np.array([1,2,3])
# make another array like a
b=a
print(f"b references the same array as a : {b} ")

# when we update array b, array a gets updated
b[0]=100
print(f"Array a is getting updated: {a} ")

# use copy function not to update orignial array
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a,"\n",b)

b references the same array as a : [1 2 3] 
Array a is getting updated: [100   2   3] 
[1 2 3] 
 [100   2   3]


# Mathematics

In [7]:
a=np.array([1,2,3,4,5])
print(a+2)
print(a*2)
print(a-2)
print(a/2)
print(a**2)
print(np.sin(a))
print(np.cos(a))


b=np.array([1,0,1,0,1])
print(a+b)

[3 4 5 6 7]
[ 2  4  6  8 10]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[2 2 4 4 6]


# Linear Algebra

In [8]:
a= np.ones(shape=(2,3))
b=np.full(shape=(3,2),fill_value=2)

# matrix multiplication
print(f"Matrix multiplication :\n{np.matmul(a,b)} ")

# Determinant of matrix
a=np.identity(5)
print(f"Determinant of identity matrix: {np.linalg.det(a)} ")

Matrix multiplication :
[[6. 6.]
 [6. 6.]] 
Determinant of identity matrix: 1.0 


# Statistics

In [9]:
a=np.array([[1,4,9],[3,12,6]])
print(a,"\n\n")
# find over all minimum
print(f"Minimum value is : {np.min(a)} ")
# find min in each column
print(f"Min in each column: {np.min(a, axis=0)}")
# find min in each row
print(f"Min in each row: {np.min(a, axis=1)}")


# find over all maximum
print(f"Maximum value is : {np.max(a)} ")
# find max in each row
print(f"Max in each row: {np.max(a,axis=1)} ")
# find max in each column 
print(f"Max in each column : {np.max(a,axis=0)} ")

# sum all element in matrix
print(f"Sum of all elements : {np.sum(a)} ")
# sum all elements in row and column
print(f"Sum of column elements: {np.sum(a,axis=0)} ")
print(f"Sum of row elements: {np.sum(a,axis=1)} ")

[[ 1  4  9]
 [ 3 12  6]] 


Minimum value is : 1 
Min in each column: [1 4 6]
Min in each row: [1 3]
Maximum value is : 12 
Max in each row: [ 9 12] 
Max in each column : [ 3 12  9] 
Sum of all elements : 35 
Sum of column elements: [ 4 16 15] 
Sum of row elements: [14 21] 


# Reorganizing arrays

In [10]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# reshape the array
print(f"\nReshaped the array: {before.reshape(4,2)}  ")

# vertical stacking 
a=np.array([1,2,3])
b=np.array([4,5,6])
print(f"Vertical stacking:\n{np.vstack([a,a,b,b])} ")

# horizontal stacking
print(f"Horizontal stacking:\n{np.hstack([a,b])} ")

[[1 2 3 4]
 [5 6 7 8]]

Reshaped the array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]  
Vertical stacking:
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]] 
Horizontal stacking:
[1 2 3 4 5 6] 


# Load Data from file

In [11]:
file_data=np.genfromtxt('data.csv',delimiter=',',skip_header=1)
print(file_data)

# convert into int
print(f"\n\nConvert into int:\n{file_data.astype('int32')} ")

[[ 1.6   7.22]
 [13.09 32.41]
 [ 6.97 17.47]]


Convert into int:
[[ 1  7]
 [13 32]
 [ 6 17]] 


# Boolean masking and Advanced indexing

In [12]:
# check what all values greater than 10 AND less than 30
print(f" check what all values greater than 10 \n{(file_data>10) & (file_data<30)}")

# accesses multiple elements at indices 1, 2, and 8.
a=np.array([1,2,3,4,5,6,7,8,9,0])
a[[1,2,8]]

 check what all values greater than 10 
[[False False]
 [ True False]
 [False  True]]


array([2, 3, 9])

In [13]:
# Try to access the element
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(f"Array:\n{a} ")

# Access number 11,12,16,17
print(f"\n\nAccess Number 11,12,16,17 :\n{a[2:4,0:2]} ")

# Access number 2,8,14,20
print(f"\n\nAccess number 2,8,14,20:\n{a[[0,1,2,3],[1,2,3,4]]} ")

# Access number 4,5,24,25,29,30
print(f"\n\nAccess number 4,5,24,25,29,30 :\n{a[[0,4,5],3:]}  ")

Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 


Access Number 11,12,16,17 :
[[11 12]
 [16 17]] 


Access number 2,8,14,20:
[ 2  8 14 20] 


Access number 4,5,24,25,29,30 :
[[ 4  5]
 [24 25]
 [29 30]]  
