# Tensor flow Fundamental

## what is tensor
A tensor is a container for numbers, like a single number, a list, a table, or a higher-dimensional array.  Neural networks usually take inputs as tensors so they can perform calculations efficiently.

A tensor can have any number of dimensions. Scalar, vector, and matrix are special names for tensors with 0, 1, and 2 dimensions.

In [1]:
# Import
import tensorflow as tf

In [2]:
# get the version of tensorflow
print(f"Version of tensorflow: {tf.__version__} ")

# create tensor with tf.constant()
scalar=tf.constant(7)
print("\nScalar")
print(scalar)

# Check the dimension of dimension
print(f"Dimension of scalar: {scalar.ndim} ")

# Create a vector and check dimension
vector=tf.constant([10,10,20])
print("\nVector")
print(vector)
print(f"Dimension of vector: {vector.ndim} ")

# Create a matrix and check dimension
matrix=tf.constant([[10,7],[7,10]])
print("\nMatrix")
print(matrix)
print(f"Dimension of matrix: {matrix.ndim} ")

# Create another matrix and change the datatype
another_matrix=tf.constant([[10.,7.],
                           [3.,2.],
                           [8.,9.]],dtype=tf.float16)
print("\nAnother Matrix")
print(another_matrix)
print(f"Dimension of another matrix: {another_matrix.ndim} ")

# Create tensor and check dimension
tensor=tf.constant([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                   [10,11,12]],
                   [[13,14,15],
                   [16,17,18]]])
print("\nTensor")
print(tensor)
print(f"Dimension of tensor: {tensor.ndim} ")

Version of tensorflow: 2.21.0 

Scalar
tf.Tensor(7, shape=(), dtype=int32)
Dimension of scalar: 0 

Vector
tf.Tensor([10 10 20], shape=(3,), dtype=int32)
Dimension of vector: 1 

Matrix
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
Dimension of matrix: 2 

Another Matrix
tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
Dimension of another matrix: 2 

Tensor
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
Dimension of tensor: 3 


## Create tensor with tf.variable

In [3]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
print(changeable_tensor,"\n",unchangeable_tensor)

# Change one element and see in changeable tensor
print(f"\n Before change: {changeable_tensor}")
changeable_tensor[0].assign(7)
print(f"After change: {changeable_tensor}")

# Change one element and see in unchangeable tensor
unchangeable_tensor[0].assign(10) # We will get error

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)> 
 tf.Tensor([10  7], shape=(2,), dtype=int32)

 Before change: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
After change: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensor

In [4]:
# generate same tensor as we use same seed
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(5,3))
print(random_1)

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(5,3))
print(random_2)

# check if two tensor are same
print("\n")
print(random_1==random_2)

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535805 ]
 [-0.57166284  0.1480774  -0.23362993]
 [-0.3522796   0.40621263 -1.0523509 ]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646 -0.7535805 ]
 [-0.57166284  0.1480774  -0.23362993]
 [-0.3522796   0.40621263 -1.0523509 ]], shape=(5, 3), dtype=float32)


tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(5, 3), dtype=bool)


# Shuffle elements in tensor

In [5]:
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
print(f"Before shuffle:\n{not_shuffled}\n ")
# shuffle the tensor
print(tf.random.shuffle(not_shuffled)) # keep running and it changes every time


Before shuffle:
[[10  7]
 [ 3  4]
 [ 2  5]]
 
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


In [6]:
# to get same shuffle all  the time
tf.random.set_seed(42) # global level random seed
print("\n\n",tf.random.shuffle(not_shuffled,seed=42)) # operational level random seed



 tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


# Other ways to create tensor

In [7]:
print(tf.ones([10,9]))
print(tf.zeros([2,3]))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 9), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# Numpy to tensor

In [8]:
 # Create numpy array
import numpy as np
numpy_1=np.arange(1,25,dtype=np.int32)

In [9]:
 # convert into tensor with differnet shape
tensor_1=tf.constant(numpy_1,shape=(6,4))
print(tensor_1)
tensor_2=tf.constant(numpy_1,shape=(2,6,2))
print(tensor_2)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]], shape=(6, 4), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]], shape=(2, 6, 2), dtype=int32)


# Getting more informations from tensor